name:                rc
version:             0.3.0.0
github:              "masterdezign/rc"
license:             BSD3
author:              "Bogdan Penkovsky"
maintainer:          "dev () penkovsky dot com"
copyright:           "Bogdan Penkovsky"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Reservoir Computing, fast RNNs
category:            Machine Learning

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/masterdezign/rc#readme>

dependencies:
- base >= 4.7 && < 5
- dde >= 0.3.0
- hmatrix >= 0.18.1.0
- Learning >= 0.1.0
- linear
- random
- vector

library:
  source-dirs: rc

executables:
  ntc:
    main:                Main.hs
    source-dirs:         examples/NTC
    dependencies:
    - rc

tests:
  rc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rc
